theme: jekyll-theme-cayman

# Name of your site (displayed in the header)
name: El Sureste Se Levanta

# Short bio or description (displayed in the header)
description: Iniciativa para ayudar al Sureste de PR a raíz del huracán María

# Includes an icon in the footer for each username you enter
footer-links:
  facebook: groups/suresteselevanta/