theme: jekyll-theme-cayman

# Name of your site (displayed in the header)
name: El Sureste Se Levanta

# Short bio or description (displayed in the header)
description: Esta es una iniciativa para ayudar a nuestra gente de Guayama, Arroyo y Patillas a raíz del huracán María

avatar: https://github.com/friveramariani/suresteselevanta/blob/master/images/Arroyo-Guayama%20-Patillas.png

# Includes an icon in the footer for each username you enter
footer-links:
  facebook: groups/suresteselevanta/